from typing import List, Dict, Any

SCENARIO_TEMPLATES: List[Dict[str, Any]] = [{'scenario_id': 'sc_low_nitrogen',
  'title': 'Nitrogen Deficiency Detected',
  'category': 'Nutrient Deficiency',
  'description': 'Available soil nitrogen has fallen to 28 mg/kg, indicating severe nitrogen hunger during peak '
                 'vegetative growth.',
  'tags': ['Nutrient', 'Nitrogen', 'Soil Health'],
  'changes_summary': ['Soil Nitrogen decreased from 58 mg/kg to 28 mg/kg (Deficient)',
                      'Soil Health score dropped due to nutrient imbalance',
                      'Chlorophyll synthesis risk flagged for vegetative rice'],
  'what_should_i_do': ['Apply neem-coated urea or organic compost based on soil test target',
                       'Split nitrogen application to prevent leaching losses',
                       'Re-check soil NPK levels in 5 days after application'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 480,
                      'soil_health_score': 54,
                      'yield_impact': '-12% potential yield loss if untreated',
                      'yield_impact_bn': 'চিকিৎসা না করলে সম্ভাব্য ফলন ১২% পর্যন্ত কমতে পারে'},
  'target_state': {'nitrogen': 28.0,
                   'phosphorus': 68.0,
                   'potassium': 62.0,
                   'ph': 6.3,
                   'ec': 0.65,
                   'soil_moisture': 58.0,
                   'soil_temperature': 27.8,
                   'air_temperature': 29.5,
                   'humidity': 68.0,
                   'rain_probability': 15.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.2},
  'title_bn': 'নাইট্রোজেনের ঘাটতি শনাক্ত হয়েছে',
  'category_bn': 'পুষ্টির ঘাটতি',
  'description_bn': 'মাটিতে উপলব্ধ নাইট্রোজেন ২৮ মিগ্রা/কেজিতে নেমে গেছে, যা সক্রিয় বৃদ্ধি পর্যায়ে তীব্র নাইট্রোজেন '
                    'ঘাটতির ইঙ্গিত দেয়.',
  'tags_bn': ['পুষ্টি', 'নাইট্রোজেন', 'মাটির স্বাস্থ্য'],
  'changes_summary_bn': ['মাটির নাইট্রোজেন ৫৮ মিগ্রা/কেজি থেকে কমে ২৮ মিগ্রা/কেজি হয়েছে (ঘাটতি)',
                         'পুষ্টির ভারসাম্যহীনতার কারণে মাটির স্বাস্থ্য স্কোর কমেছে',
                         'ধানের সক্রিয় বৃদ্ধিতে ক্লোরোফিল সংশ্লেষণের ঝুঁকি শনাক্ত হয়েছে'],
  'what_should_i_do_bn': ['মাটির পরীক্ষার লক্ষ্যমাত্রা অনুযায়ী নিম-কোটেড ইউরিয়া বা জৈব কম্পোস্ট প্রয়োগ করুন',
                          'নাইট্রোজেন ধুয়ে যাওয়ার ক্ষতি কমাতে ভাগ করে নাইট্রোজেন প্রয়োগ করুন',
                          'প্রয়োগের ৫ দিন পর মাটির NPK মাত্রা পুনরায় পরীক্ষা করুন']},
 {'scenario_id': 'sc_excess_nitrogen',
  'title': 'Excess Nitrogen & Leaching Hazard',
  'category': 'Over-fertilization',
  'description': 'Excessive nitrogen (135 mg/kg) detected. Excessive vegetative growth increases lodging risk, pest '
                 'susceptibility, and runoff pollution.',
  'tags': ['Over-application', 'Environmental Risk', 'Economics'],
  'changes_summary': ['Soil Nitrogen surged to 135 mg/kg (Excessive)',
                      'Environmental runoff risk shifted to HIGH',
                      'Farm economics detects ₹1,200 in wasted fertilizer expenditure'],
  'what_should_i_do': ['Halt all nitrogenous fertilizer additions immediately',
                       'Ensure controlled irrigation to prevent groundwater nitrate leaching',
                       'Monitor crop for sucking pests attracted to lush vegetative tissue'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 0,
                      'soil_health_score': 61,
                      'environmental_hazard': 'Nitrate leaching risk elevated',
                      'environmental_hazard_bn': 'নাইট্রেট লিচিংয়ের ঝুঁকি বেড়েছে'},
  'target_state': {'nitrogen': 135.0,
                   'phosphorus': 70.0,
                   'potassium': 65.0,
                   'ph': 6.8,
                   'ec': 1.45,
                   'soil_moisture': 62.0,
                   'soil_temperature': 27.0,
                   'air_temperature': 29.0,
                   'humidity': 70.0,
                   'rain_probability': 30.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.4},
  'title_bn': 'অতিরিক্ত নাইট্রোজেন ও লিচিং ঝুঁকি',
  'category_bn': 'অতিরিক্ত সার প্রয়োগ',
  'description_bn': '১৩৫ মিগ্রা/কেজি অতিরিক্ত নাইট্রোজেন শনাক্ত হয়েছে। অতিরিক্ত গাছের বৃদ্ধি হেলে পড়ার ঝুঁকি, '
                    'পোকামাকড়ের আক্রমণ এবং রানঅফ দূষণ বাড়ায়।',
  'tags_bn': ['অতিরিক্ত প্রয়োগ', 'পরিবেশগত ঝুঁকি', 'অর্থনীতি'],
  'changes_summary_bn': ['মাটির নাইট্রোজেন বেড়ে ১৩৫ মিগ্রা/কেজি হয়েছে (অতিরিক্ত)',
                         'পরিবেশগত রানঅফ ঝুঁকি HIGH হয়েছে',
                         'কৃষি অর্থনীতি ১,২০০ টাকা অপচয় হওয়া সার খরচ শনাক্ত করেছে'],
  'what_should_i_do_bn': ['অবিলম্বে সব নাইট্রোজেনযুক্ত সার প্রয়োগ বন্ধ করুন',
                          'ভূগর্ভস্থ জলে নাইট্রেট লিচিং কমাতে নিয়ন্ত্রিত সেচ নিশ্চিত করুন',
                          'অতিরিক্ত সবুজ গাছপালায় আকৃষ্ট চোষক পোকামাকড়ের জন্য ফসল পর্যবেক্ষণ করুন']},
 {'scenario_id': 'sc_low_moisture_water_stress',
  'title': 'Soil Moisture Deficit & Water Stress',
  'category': 'Water Stress',
  'description': 'Root zone soil moisture dropped to 23%, falling below the critical threshold (45%) for rice paddy '
                 'cultivation.',
  'tags': ['Irrigation Required', 'Pump ON', 'Crop Stress'],
  'changes_summary': ['Soil moisture dropped to 23% (Critical Deficit)',
                      'Smart Irrigation engine recommends IMMEDIATE PUMP ACTIVATION',
                      'Virtual pump switched to ON in simulation',
                      'Crop water stress index flagged as HIGH'],
  'what_should_i_do': ['Activate irrigation pump for approximately 2.5 hours',
                       'Deliver 18,500 Litres of water across 2.4 acres',
                       'Apply light mulching to conserve topsoil moisture'],
  'expected_impact': {'water_requirement_l': 18500,
                      'estimated_cost_inr': 280,
                      'soil_health_score': 52,
                      'pump_status': 'ON',
                      'pump_status_bn': 'চালু'},
  'target_state': {'soil_moisture': 23.0,
                   'soil_temperature': 32.5,
                   'nitrogen': 54.0,
                   'phosphorus': 66.0,
                   'potassium': 60.0,
                   'ph': 6.5,
                   'ec': 0.95,
                   'air_temperature': 34.0,
                   'humidity': 45.0,
                   'rain_probability': 10.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.3},
  'title_bn': 'মাটির আর্দ্রতার ঘাটতি ও জলীয় চাপ',
  'category_bn': 'জলীয় চাপ',
  'description_bn': 'শিকড়ের অঞ্চলের মাটির আর্দ্রতা ২৩%-এ নেমে গেছে, যা ধানের জন্য গুরুত্বপূর্ণ ৪৫% সীমার নিচে।',
  'tags_bn': ['সেচ প্রয়োজন', 'পাম্প চালু', 'ফসলের চাপ'],
  'changes_summary_bn': ['মাটির আর্দ্রতা ২৩%-এ নেমেছে (গুরুতর ঘাটতি)',
                         'স্মার্ট সেচ ব্যবস্থা অবিলম্বে পাম্প চালুর সুপারিশ করছে',
                         'সিমুলেশনে ভার্চুয়াল পাম্প চালু হয়েছে',
                         'ফসলের জলীয় চাপ সূচক HIGH হিসেবে শনাক্ত হয়েছে'],
  'what_should_i_do_bn': ['প্রায় ২.৫ ঘণ্টার জন্য সেচ পাম্প চালু করুন',
                          '২.৪ একর জমিতে ১৮,৫০০ লিটার জল দিন',
                          'উপরের মাটির আর্দ্রতা ধরে রাখতে হালকা মালচিং করুন']},
 {'scenario_id': 'sc_high_moisture_high_rain',
  'title': 'High Moisture + Impending Monsoon Downpour',
  'category': 'Water Conservation',
  'description': 'Soil moisture is 79% and satellite weather forecasts an 88% probability of 28mm precipitation in the '
                 'next 12 hours.',
  'tags': ['Delay Irrigation', 'Water Saving', 'Cost Saving'],
  'changes_summary': ['Soil moisture is high (79%)',
                      'Rain probability surged to 88% (Expected rainfall: 28 mm)',
                      'Smart Irrigation cancels scheduled watering — saves 22,000 Litres of groundwater',
                      'Farm Economics logs ₹420 electricity/fuel savings'],
  'what_should_i_do': ['DO NOT IRRIGATE — allow natural rainfall to replenish soil',
                       'Inspect field bunds and drainage outlets to avoid waterlogging',
                       'Postpone foliar pesticide or urea spraying until after the rain'],
  'expected_impact': {'water_saved_l': 22000,
                      'estimated_cost_saving_inr': 420,
                      'soil_health_score': 82,
                      'pump_status': 'OFF',
                      'pump_status_bn': 'চালু'},
  'target_state': {'soil_moisture': 79.0,
                   'soil_temperature': 25.0,
                   'nitrogen': 56.0,
                   'phosphorus': 70.0,
                   'potassium': 64.0,
                   'ph': 6.6,
                   'ec': 0.72,
                   'air_temperature': 26.5,
                   'humidity': 89.0,
                   'rain_probability': 88.0,
                   'expected_rainfall': 28.0,
                   'organic_matter': 1.55},
  'title_bn': 'অতিরিক্ত আর্দ্রতা ও আসন্ন বর্ষার ভারী বৃষ্টি',
  'category_bn': 'জল সংরক্ষণ',
  'description_bn': 'মাটির আর্দ্রতা ৭৯% এবং স্যাটেলাইট আবহাওয়া পূর্বাভাসে আগামী ১২ ঘণ্টায় ২৮ মিমি বৃষ্টির সম্ভাবনা '
                    '৮৮%।',
  'tags_bn': ['সেচ বিলম্ব', 'জল সাশ্রয়', 'খরচ সাশ্রয়'],
  'changes_summary_bn': ['মাটির আর্দ্রতা বেশি (৭৯%)',
                         'বৃষ্টির সম্ভাবনা ৮৮%-এ বেড়েছে (প্রত্যাশিত বৃষ্টি: ২৮ মিমি)',
                         'স্মার্ট সেচ নির্ধারিত জল দেওয়া বাতিল করেছে — ২২,০০০ লিটার ভূগর্ভস্থ জল সাশ্রয়',
                         'কৃষি অর্থনীতিতে ৪২০ টাকা বিদ্যুৎ/জ্বালানি সাশ্রয় নথিভুক্ত হয়েছে'],
  'what_should_i_do_bn': ['সেচ দেবেন না — প্রাকৃতিক বৃষ্টিতে মাটি পুনরায় আর্দ্র হতে দিন',
                          'জলাবদ্ধতা এড়াতে জমির বাঁধ ও নিষ্কাশন পথ পরীক্ষা করুন',
                          'বৃষ্টির পর পর্যন্ত পাতায় কীটনাশক বা ইউরিয়া স্প্রে স্থগিত রাখুন']},
 {'scenario_id': 'sc_acidic_soil',
  'title': 'Acidic Soil Condition (Low pH)',
  'category': 'Soil Degradation',
  'description': 'Soil pH has dropped to 5.1 (Strongly Acidic), impairing phosphorus availability and increasing '
                 'aluminum/iron toxicity risk.',
  'tags': ['Low pH', 'Soil Amendment', 'Agricultural Lime'],
  'changes_summary': ['Soil pH dropped to 5.1 (Sub-optimal for crop)',
                      'Phosphorus fixation risk increased',
                      'Soil Health score penalized for chemical degradation'],
  'what_should_i_do': ['Apply agricultural lime (calcium carbonate) or dolomite at 200 kg/acre',
                       'Incorporate well-decomposed Farmyard Manure (FYM) to buffer pH',
                       'Avoid acidifying fertilizers like ammonium sulfate until pH normalizes'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 850,
                      'soil_health_score': 48,
                      'nutrient_availability': 'Restores P and K uptake',
                      'nutrient_availability_bn': 'P ও K গ্রহণ পুনরুদ্ধার করে'},
  'target_state': {'ph': 5.1,
                   'nitrogen': 48.0,
                   'phosphorus': 35.0,
                   'potassium': 52.0,
                   'ec': 0.6,
                   'soil_moisture': 60.0,
                   'soil_temperature': 26.8,
                   'air_temperature': 28.5,
                   'humidity': 65.0,
                   'rain_probability': 25.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.1},
  'title_bn': 'অম্লীয় মাটির অবস্থা (কম pH)',
  'category_bn': 'মাটির অবক্ষয়',
  'description_bn': 'মাটির pH ৫.১-এ নেমেছে (তীব্র অম্লীয়), ফলে ফসফরাসের প্রাপ্যতা কমছে এবং অ্যালুমিনিয়াম/লোহা '
                    'বিষক্রিয়ার ঝুঁকি বাড়ছে।',
  'tags_bn': ['কম pH', 'মাটি সংশোধন', 'কৃষি চুন'],
  'changes_summary_bn': ['মাটির pH ৫.১-এ নেমেছে (ফসলের জন্য অনুকূল নয়)',
                         'ফসফরাস আটকে যাওয়ার ঝুঁকি বেড়েছে',
                         'রাসায়নিক অবক্ষয়ের কারণে মাটির স্বাস্থ্য স্কোর কমেছে'],
  'what_should_i_do_bn': ['প্রতি একরে ২০০ কেজি কৃষি চুন (ক্যালসিয়াম কার্বোনেট) বা ডলোমাইট প্রয়োগ করুন',
                          'pH ভারসাম্য রাখতে ভালোভাবে পচা গোবর সার (FYM) মাটিতে মেশান',
                          'pH স্বাভাবিক না হওয়া পর্যন্ত অ্যামোনিয়াম সালফেটের মতো অম্লীয় সার এড়িয়ে চলুন']},
 {'scenario_id': 'sc_alkaline_soil',
  'title': 'Alkaline Soil & Micronutrient Lockup',
  'category': 'Soil Degradation',
  'description': 'Soil pH reached 8.4 (Alkaline/Calcareous), reducing micronutrient solubility (Zinc, Iron, Manganese) '
                 'and crop vigor.',
  'tags': ['High pH', 'Gypsum', 'Micronutrients'],
  'changes_summary': ['Soil pH elevated to 8.4 (Alkaline)',
                      'Zinc and Iron availability severely restricted',
                      'Soil Degradation risk elevated to MODERATE'],
  'what_should_i_do': ['Apply agricultural gypsum (calcium sulfate) or elemental sulfur',
                       'Foliar spray with chelated Zinc (Zn-EDTA 0.5%) and Iron',
                       'Increase green manuring with Dhaincha/Sesbania'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 920,
                      'soil_health_score': 53,
                      'remediation_timeline': '2-3 weeks with organic incorporation',
                      'remediation_timeline_bn': 'জৈব পদার্থ মেশালে ২-৩ সপ্তাহ'},
  'target_state': {'ph': 8.4,
                   'nitrogen': 52.0,
                   'phosphorus': 45.0,
                   'potassium': 75.0,
                   'ec': 1.2,
                   'soil_moisture': 55.0,
                   'soil_temperature': 28.2,
                   'air_temperature': 30.0,
                   'humidity': 62.0,
                   'rain_probability': 15.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 0.95},
  'title_bn': 'ক্ষারীয় মাটি ও মাইক্রোনিউট্রিয়েন্ট আটকে যাওয়া',
  'category_bn': 'মাটির অবক্ষয়',
  'description_bn': 'মাটির pH ৮.৪-এ পৌঁছেছে (ক্ষারীয়/ক্যালক্যারিয়াস), ফলে জিঙ্ক, লোহা ও ম্যাঙ্গানিজের দ্রাব্যতা এবং '
                    'ফসলের বৃদ্ধি কমছে।',
  'tags_bn': ['উচ্চ pH', 'জিপসাম', 'মাইক্রোনিউট্রিয়েন্ট'],
  'changes_summary_bn': ['মাটির pH ৮.৪-এ বেড়েছে (ক্ষারীয়)',
                         'জিঙ্ক ও লোহার প্রাপ্যতা গুরুতরভাবে কমেছে',
                         'মাটির অবক্ষয়ের ঝুঁকি MODERATE পর্যায়ে বেড়েছে'],
  'what_should_i_do_bn': ['কৃষি জিপসাম (ক্যালসিয়াম সালফেট) বা মৌলিক সালফার প্রয়োগ করুন',
                          'চিলেটেড জিঙ্ক (Zn-EDTA ০.৫%) ও লোহা দিয়ে পাতায় স্প্রে করুন',
                          'ঢেঁইচা/সেসবানিয়ার সবুজ সার প্রয়োগ বাড়ান']},
 {'scenario_id': 'sc_high_salinity_ec',
  'title': 'High Soil Salinity & EC Warning',
  'category': 'Salinity Hazard',
  'description': 'Electrical Conductivity measured at 2.45 dS/m, indicating root osmotic stress and poor drainage or '
                 'brackish borewell water.',
  'tags': ['Salinity', 'High EC', 'Root Stress'],
  'changes_summary': ['Soil EC surged to 2.45 dS/m (Saline Risk Threshold > 2.0)',
                      'Crop water extraction impeded due to osmotic pressure',
                      'AI Advisor flags irrigation water quality test requirement'],
  'what_should_i_do': ['Provide deep leaching irrigation with low-saline fresh water',
                       'Avoid potassium chloride (MOP) and sodium-bearing inputs',
                       'Construct deep cross-field sub-surface drainage trenches'],
  'expected_impact': {'water_requirement_l': 12000,
                      'estimated_cost_inr': 350,
                      'soil_health_score': 46,
                      'hazard_level': 'Osmotic root restriction',
                      'hazard_level_bn': 'শিকড়ে অসমোটিক বাধা'},
  'target_state': {'ec': 2.45,
                   'soil_moisture': 52.0,
                   'soil_temperature': 29.0,
                   'nitrogen': 65.0,
                   'phosphorus': 58.0,
                   'potassium': 88.0,
                   'ph': 7.9,
                   'air_temperature': 32.0,
                   'humidity': 58.0,
                   'rain_probability': 20.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.05},
  'title_bn': 'মাটিতে উচ্চ লবণাক্ততা ও EC সতর্কতা',
  'category_bn': 'লবণাক্ততার ঝুঁকি',
  'description_bn': 'বৈদ্যুতিক পরিবাহিতা ২.৪৫ dS/m মাপা হয়েছে, যা শিকড়ে অসমোটিক চাপ এবং দুর্বল নিষ্কাশন বা লবণাক্ত '
                    'নলকূপের জলের ইঙ্গিত দেয়।',
  'tags_bn': ['লবণাক্ততা', 'উচ্চ EC', 'শিকড়ের চাপ'],
  'changes_summary_bn': ['মাটির EC বেড়ে ২.৪৫ dS/m হয়েছে (লবণাক্ততার ঝুঁকি সীমা > ২.০)',
                         'অসমোটিক চাপের কারণে ফসলের জল শোষণ বাধাগ্রস্ত হচ্ছে',
                         'AI Advisor সেচের জলের গুণমান পরীক্ষা করার প্রয়োজনীয়তা জানিয়েছে'],
  'what_should_i_do_bn': ['কম লবণাক্ত তাজা জল দিয়ে গভীর লিচিং সেচ দিন',
                          'পটাশিয়াম ক্লোরাইড (MOP) ও সোডিয়ামযুক্ত উপাদান এড়িয়ে চলুন',
                          'গভীর ক্রস-ফিল্ড ভূগর্ভস্থ নিষ্কাশন নালা তৈরি করুন']},
 {'scenario_id': 'sc_heat_stress_dry',
  'title': 'Extreme Heat Stress & Evaporative Deficit',
  'category': 'Microclimate Stress',
  'description': 'Ambient temperature spiked to 39.2°C with low humidity (36%) and soil moisture declining rapidly to '
                 '28%.',
  'tags': ['Heatwave', 'Vapor Pressure Deficit', 'Cooling Irrigation'],
  'changes_summary': ['Air temperature spiked to 39.2°C (Heatwave alert)',
                      'Evaporative demand increased 40%',
                      'Crop health score declined from 84% to 58%'],
  'what_should_i_do': ['Perform light evening micro-sprinkler irrigation to cool microclimate',
                       'Apply anti-transpirant spray (KNO3 1% or kaolin clay spray)',
                       'Avoid midday intercultural farm operations'],
  'expected_impact': {'water_requirement_l': 14000,
                      'estimated_cost_inr': 240,
                      'soil_health_score': 58,
                      'heat_mitigation': 'Lowers canopy temperature by 3-4°C',
                      'heat_mitigation_bn': 'পাতার তাপমাত্রা ৩-৪°C কমায়'},
  'target_state': {'air_temperature': 39.2,
                   'humidity': 36.0,
                   'soil_moisture': 28.0,
                   'soil_temperature': 34.5,
                   'nitrogen': 52.0,
                   'phosphorus': 64.0,
                   'potassium': 58.0,
                   'ph': 6.6,
                   'ec': 1.1,
                   'rain_probability': 5.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.3},
  'title_bn': 'চরম তাপজনিত চাপ ও বাষ্পীভবন ঘাটতি',
  'category_bn': 'ক্ষতিকর জলবায়ু চাপ',
  'description_bn': 'তাপমাত্রা ৩৯.২°C-এ বেড়েছে, আর্দ্রতা কমে ৩৬% এবং মাটির আর্দ্রতা দ্রুত ২৮%-এ নেমেছে।',
  'tags_bn': ['তাপপ্রবাহ', 'বাষ্পচাপ ঘাটতি', 'শীতল সেচ'],
  'changes_summary_bn': ['বাতাসের তাপমাত্রা ৩৯.২°C-এ বেড়েছে (তাপপ্রবাহ সতর্কতা)',
                         'বাষ্পীভবনের চাহিদা ৪০% বেড়েছে',
                         'ফসলের স্বাস্থ্য স্কোর ৮৪% থেকে ৫৮%-এ নেমেছে'],
  'what_should_i_do_bn': ['মাইক্রোক্লাইমেট ঠান্ডা করতে সন্ধ্যায় হালকা মাইক্রো-স্প্রিঙ্কলার সেচ দিন',
                          'অ্যান্টি-ট্রান্সপিরেন্ট স্প্রে (KNO3 ১% বা কাওলিন ক্লে) প্রয়োগ করুন',
                          'দুপুরে আন্তঃচাষের কাজ এড়িয়ে চলুন']},
 {'scenario_id': 'sc_healthy_optimal_farm',
  'title': 'Healthy Balanced Farm (Optimal Baseline)',
  'category': 'Optimal',
  'description': 'All soil chemical, physical, and atmospheric parameters are balanced in peak agronomic ranges for '
                 'rice cultivation.',
  'tags': ['Balanced', 'High Soil Score', 'Steady State'],
  'changes_summary': ['Soil Health score: 86/100 (Optimal)',
                      'NPK ratio (62:74:66) well balanced',
                      'Soil moisture (64%) within ideal field capacity range',
                      'No active degradation hazards'],
  'what_should_i_do': ['Maintain current sustainable irrigation and nutrient schedule',
                       'Conduct routine scout for early stem borer or weed presence',
                       'Record growth stage transition (Active Tillering)'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 0,
                      'soil_health_score': 86,
                      'profit_projection': 'Peak potential revenue track',
                      'profit_projection_bn': 'সর্বোচ্চ সম্ভাব্য আয়ের ধারা'},
  'target_state': {'soil_moisture': 64.0,
                   'soil_temperature': 26.8,
                   'ph': 6.5,
                   'ec': 0.78,
                   'nitrogen': 62.0,
                   'phosphorus': 74.0,
                   'potassium': 66.0,
                   'organic_matter': 1.65,
                   'air_temperature': 28.4,
                   'humidity': 68.0,
                   'rain_probability': 25.0,
                   'expected_rainfall': 0.0,
                   'wind_speed': 11.0},
  'title_bn': 'সুস্থ ভারসাম্যপূর্ণ খামার (আদর্শ ভিত্তি)',
  'category_bn': 'আদর্শ',
  'description_bn': 'ধান চাষের সর্বোত্তম কৃষিবৈজ্ঞানিক সীমার মধ্যে মাটির রাসায়নিক, ভৌত ও বায়ুমণ্ডলীয় সব পরামিতি '
                    'ভারসাম্যপূর্ণ।',
  'tags_bn': ['ভারসাম্যপূর্ণ', 'উচ্চ মাটি স্কোর', 'স্থিতিশীল অবস্থা'],
  'changes_summary_bn': ['মাটির স্বাস্থ্য স্কোর: ৮৬/১০০ (আদর্শ)',
                         'NPK অনুপাত (৬২:৭৪:৬৬) ভালোভাবে ভারসাম্যপূর্ণ',
                         'মাটির আর্দ্রতা (৬৪%) আদর্শ ফিল্ড ক্যাপাসিটি সীমার মধ্যে',
                         'কোনো সক্রিয় অবক্ষয়জনিত ঝুঁকি নেই'],
  'what_should_i_do_bn': ['বর্তমান টেকসই সেচ ও পুষ্টি ব্যবস্থাপনা বজায় রাখুন',
                          'কাণ্ড ছিদ্রকারী পোকা বা আগাছার প্রাথমিক উপস্থিতির জন্য নিয়মিত পর্যবেক্ষণ করুন',
                          'বৃদ্ধির পর্যায় পরিবর্তন (সক্রিয় কুশি গঠন) নথিভুক্ত করুন']},
 {'scenario_id': 'sc_phosphorus_deficiency',
  'title': 'Phosphorus Hunger & Stunted Root Growth',
  'category': 'Nutrient Deficiency',
  'description': 'Available phosphorus dropped to 22 mg/kg. Crop shows purple-tinted lower leaves and impaired root '
                 'establishment.',
  'tags': ['Phosphorus', 'Root Development', 'Single Super Phosphate'],
  'changes_summary': ['Soil Phosphorus plummeted to 22 mg/kg (Deficient)',
                      'Root establishment index reduced',
                      'AI Advisor recommends localized SSP or rock phosphate'],
  'what_should_i_do': ['Apply Single Super Phosphate (SSP) or DAP banded near root zone',
                       'Inoculate with Phosphate Solubilizing Bacteria (PSB) biofertilizer',
                       'Verify soil moisture is adequate to allow phosphate dissolution'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 620,
                      'soil_health_score': 56,
                      'root_recovery': 'Improves tillering within 7 days',
                      'root_recovery_bn': '৭ দিনের মধ্যে কুশি গঠন উন্নত করে'},
  'target_state': {'phosphorus': 22.0,
                   'nitrogen': 58.0,
                   'potassium': 65.0,
                   'ph': 6.1,
                   'ec': 0.7,
                   'soil_moisture': 59.0,
                   'soil_temperature': 27.0,
                   'air_temperature': 29.0,
                   'humidity': 66.0,
                   'rain_probability': 20.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.25},
  'title_bn': 'ফসফরাসের ঘাটতি ও শিকড়ের বৃদ্ধি বাধাগ্রস্ত',
  'category_bn': 'পুষ্টির ঘাটতি',
  'description_bn': 'উপলব্ধ ফসফরাস ২২ মিগ্রা/কেজিতে নেমেছে। ফসলে নিচের পাতায় বেগুনি আভা এবং শিকড় স্থাপনে সমস্যা দেখা '
                    'যাচ্ছে।',
  'tags_bn': ['ফসফরাস', 'শিকড়ের বৃদ্ধি', 'সিঙ্গেল সুপার ফসফেট'],
  'changes_summary_bn': ['মাটির ফসফরাস ২২ মিগ্রা/কেজিতে নেমেছে (ঘাটতি)',
                         'শিকড় স্থাপনের সূচক কমেছে',
                         'AI Advisor স্থানীয়ভাবে SSP বা রক ফসফেট ব্যবহারের সুপারিশ করছে'],
  'what_should_i_do_bn': ['শিকড়ের কাছে ব্যান্ড পদ্ধতিতে SSP বা DAP প্রয়োগ করুন',
                          'ফসফেট দ্রবীভূতকারী ব্যাকটেরিয়া (PSB) জৈবসার প্রয়োগ করুন',
                          'ফসফেট দ্রবীভূত হতে মাটির আর্দ্রতা পর্যাপ্ত আছে কিনা নিশ্চিত করুন']},
 {'scenario_id': 'sc_potassium_deficiency',
  'title': 'Potassium Deficiency & Lodging Vulnerability',
  'category': 'Nutrient Deficiency',
  'description': 'Potassium is low (26 mg/kg). Plants display marginal leaf scorching and increased vulnerability to '
                 'lodging and fungal blight.',
  'tags': ['Potassium', 'MOP', 'Disease Resistance'],
  'changes_summary': ['Soil Potassium fell to 26 mg/kg (Deficient)',
                      'Pest and disease resistance threshold compromised',
                      'Stem strength index lowered'],
  'what_should_i_do': ['Apply Muriate of Potash (MOP) or organic wood ash amendment',
                       'Foliar spray with 1% potassium sulfate for immediate absorption',
                       'Maintain balanced irrigation to assist ionic potassium mobility'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 540,
                      'soil_health_score': 58,
                      'lodging_protection': 'Reinforces cell wall lignification',
                      'lodging_protection_bn': 'কোষপ্রাচীরের লিগনিফিকেশন শক্তিশালী করে'},
  'target_state': {'potassium': 26.0,
                   'nitrogen': 60.0,
                   'phosphorus': 68.0,
                   'ph': 6.4,
                   'ec': 0.68,
                   'soil_moisture': 61.0,
                   'soil_temperature': 27.2,
                   'air_temperature': 28.8,
                   'humidity': 70.0,
                   'rain_probability': 30.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.35},
  'title_bn': 'পটাশিয়ামের ঘাটতি ও গাছ হেলে পড়ার ঝুঁকি',
  'category_bn': 'পুষ্টির ঘাটতি',
  'description_bn': 'পটাশিয়াম কমে ২৬ মিগ্রা/কেজি হয়েছে। পাতার কিনারায় পোড়া দাগ এবং গাছ হেলে পড়া ও ছত্রাকজনিত '
                    'রোগের ঝুঁকি বেড়েছে।',
  'tags_bn': ['পটাশিয়াম', 'MOP', 'রোগ প্রতিরোধ'],
  'changes_summary_bn': ['মাটির পটাশিয়াম ২৬ মিগ্রা/কেজিতে নেমেছে (ঘাটতি)',
                         'পোকা ও রোগ প্রতিরোধের সীমা ক্ষতিগ্রস্ত হয়েছে',
                         'কাণ্ডের শক্তির সূচক কমেছে'],
  'what_should_i_do_bn': ['MOP বা জৈব কাঠের ছাই প্রয়োগ করুন',
                          'দ্রুত শোষণের জন্য ১% পটাশিয়াম সালফেট পাতায় স্প্রে করুন',
                          'পটাশিয়ামের চলাচলে সহায়তা করতে ভারসাম্যপূর্ণ সেচ বজায় রাখুন']},
 {'scenario_id': 'sc_disease_humidity_risk',
  'title': 'High Humidity & Fungal Blast Epidemic Risk',
  'category': 'Crop Disease Risk',
  'description': 'Continuous relative humidity above 92% combined with warm canopy temperatures (27°C) triggers High '
                 'Fungal Blast risk.',
  'tags': ['Disease Alert', 'High Humidity', 'Preventive Bio-agent'],
  'changes_summary': ['Relative Humidity spiked to 94%',
                      'Fungal spore germination microclimate conditions ACTIVE',
                      'Crop health alert: Preventive biological spray recommended'],
  'what_should_i_do': ['Spray bio-fungicide (Trichoderma viride or Pseudomonas fluorescens)',
                       'Ensure field aeration by maintaining water flow in paddies',
                       'Refrain from high nitrogen top-dressing which exacerbates blast'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 380,
                      'soil_health_score': 70,
                      'disease_suppression': 'Prevents up to 25% foliar blast damage',
                      'disease_suppression_bn': 'পাতার ব্লাস্টের ক্ষতি ২৫% পর্যন্ত প্রতিরোধ করে'},
  'target_state': {'humidity': 94.0,
                   'air_temperature': 27.5,
                   'soil_moisture': 76.0,
                   'soil_temperature': 26.0,
                   'nitrogen': 64.0,
                   'phosphorus': 69.0,
                   'potassium': 62.0,
                   'ph': 6.5,
                   'ec': 0.8,
                   'rain_probability': 75.0,
                   'expected_rainfall': 6.5,
                   'organic_matter': 1.5},
  'title_bn': 'উচ্চ আর্দ্রতা ও ছত্রাকজনিত ব্লাস্ট মহামারির ঝুঁকি',
  'category_bn': 'ফসলের রোগের ঝুঁকি',
  'description_bn': '৯২%-এর বেশি ধারাবাহিক আপেক্ষিক আর্দ্রতা এবং ২৭°C উষ্ণ পাতার পরিবেশ উচ্চ ছত্রাকজনিত ব্লাস্ট ঝুঁকি '
                    'তৈরি করছে।',
  'tags_bn': ['রোগ সতর্কতা', 'উচ্চ আর্দ্রতা', 'প্রতিরোধী জৈব উপাদান'],
  'changes_summary_bn': ['আপেক্ষিক আর্দ্রতা ৯৪%-এ বেড়েছে',
                         'ছত্রাকের স্পোর অঙ্কুরোদ্গমের অনুকূল পরিবেশ সক্রিয়',
                         'ফসলের স্বাস্থ্য সতর্কতা: প্রতিরোধমূলক জৈব স্প্রে সুপারিশ করা হয়েছে'],
  'what_should_i_do_bn': ['জৈব ছত্রাকনাশক (Trichoderma viride বা Pseudomonas fluorescens) স্প্রে করুন',
                          'ধানের জমিতে জল চলাচল বজায় রেখে বায়ু চলাচল নিশ্চিত করুন',
                          'ব্লাস্ট বাড়তে পারে এমন উচ্চ নাইট্রোজেনের উপরিপ্রয়োগ এড়িয়ে চলুন']},
 {'scenario_id': 'sc_multi_stress_water_nitrogen',
  'title': 'Combined Water Stress + Nitrogen Deficiency',
  'category': 'Compound Stress',
  'description': 'Critical compound stress: both soil moisture (24%) and available nitrogen (22 mg/kg) have plunged '
                 'during vegetative tillering.',
  'tags': ['Dual Hazard', 'Urgent Intervention', 'Pump ON'],
  'changes_summary': ['Soil moisture dropped to 24% (Severely Dry)',
                      'Soil Nitrogen dropped to 22 mg/kg (Severely Low)',
                      'Soil Health score dropped to 41/100 (Critical)',
                      'AI Advisor issues combined fertigation advisory'],
  'what_should_i_do': ['Initiate 3-hour irrigation immediately to restore root hydration',
                       'Follow up with split-dose soluble nitrogen fertigation once moist',
                       'Do NOT apply dry granular urea on dry soil to avoid root burn'],
  'expected_impact': {'water_requirement_l': 21000,
                      'estimated_cost_inr': 720,
                      'soil_health_score': 41,
                      'yield_risk': 'High - immediate action needed',
                      'yield_risk_bn': 'উচ্চ - অবিলম্বে ব্যবস্থা প্রয়োজন'},
  'target_state': {'soil_moisture': 24.0,
                   'nitrogen': 22.0,
                   'phosphorus': 60.0,
                   'potassium': 56.0,
                   'soil_temperature': 33.0,
                   'ph': 6.3,
                   'ec': 0.75,
                   'air_temperature': 35.5,
                   'humidity': 42.0,
                   'rain_probability': 10.0,
                   'expected_rainfall': 0.0,
                   'organic_matter': 1.15},
  'title_bn': 'সম্মিলিত জলীয় চাপ ও নাইট্রোজেনের ঘাটতি',
  'category_bn': 'যৌগিক চাপ',
  'description_bn': 'গুরুতর সম্মিলিত চাপ: কুশি গঠন পর্যায়ে মাটির আর্দ্রতা ২৪% এবং উপলব্ধ নাইট্রোজেন ২২ মিগ্রা/কেজিতে '
                    'নেমে গেছে।',
  'tags_bn': ['দ্বৈত ঝুঁকি', 'জরুরি হস্তক্ষেপ', 'পাম্প চালু'],
  'changes_summary_bn': ['মাটির আর্দ্রতা ২৪%-এ নেমেছে (অত্যন্ত শুষ্ক)',
                         'মাটির নাইট্রোজেন ২২ মিগ্রা/কেজিতে নেমেছে (অত্যন্ত কম)',
                         'মাটির স্বাস্থ্য স্কোর ৪১/১০০-এ নেমেছে (গুরুতর)',
                         'AI Advisor সম্মিলিত ফার্টিগেশন পরামর্শ দিচ্ছে'],
  'what_should_i_do_bn': ['শিকড়ে জল ফিরিয়ে আনতে অবিলম্বে ৩ ঘণ্টা সেচ দিন',
                          'মাটি ভেজার পর ভাগ করে দ্রবণীয় নাইট্রোজেন ফার্টিগেশন করুন',
                          'শুষ্ক মাটিতে দানাদার ইউরিয়া দেবেন না, এতে শিকড় পুড়ে যেতে পারে']},
 {'scenario_id': 'sc_regenerative_sustainable_farm',
  'title': 'Regenerative Organic & High Carbon Soil',
  'category': 'Sustainability High',
  'description': 'High soil organic carbon (2.2%), thriving biological activity, and optimal moisture conservation '
                 'under cover crop mulching.',
  'tags': ['Carbon Sequestration', 'Eco-Friendly', 'High Profit Margin'],
  'changes_summary': ['Soil Organic Matter increased to 2.2% (Excellent structure)',
                      'Natural water retention increased by 35%',
                      'Environmental sustainability rating: A+',
                      'Chemical input savings: ₹3,200 per acre'],
  'what_should_i_do': ['Continue organic mulching and microbial Jeevamrut application',
                       'Prepare for premium organic market certification pricing',
                       'Maintain soil cover to preserve biological microbial network'],
  'expected_impact': {'water_saved_l': 32000,
                      'estimated_cost_saving_inr': 3200,
                      'soil_health_score': 93,
                      'carbon_credit': '1.2 tons CO2 equivalent captured',
                      'carbon_credit_bn': '১.২ টন CO2 সমতুল্য কার্বন ধারণ'},
  'target_state': {'organic_matter': 2.2,
                   'soil_moisture': 68.0,
                   'nitrogen': 68.0,
                   'phosphorus': 76.0,
                   'potassium': 72.0,
                   'ph': 6.7,
                   'ec': 0.65,
                   'soil_temperature': 25.5,
                   'air_temperature': 27.8,
                   'humidity': 65.0,
                   'rain_probability': 30.0,
                   'expected_rainfall': 0.0},
  'title_bn': 'পুনরুজ্জীবনমূলক জৈব ও উচ্চ কার্বনযুক্ত মাটি',
  'category_bn': 'উচ্চ টেকসইতা',
  'description_bn': '২.২% উচ্চ জৈব কার্বন, সক্রিয় জীবজগত এবং কভার ক্রপ মালচিংয়ের মাধ্যমে সর্বোত্তম আর্দ্রতা সংরক্ষণ।',
  'tags_bn': ['কার্বন সঞ্চয়', 'পরিবেশবান্ধব', 'উচ্চ লাভের মার্জিন'],
  'changes_summary_bn': ['মাটির জৈব পদার্থ ২.২%-এ বেড়েছে (চমৎকার গঠন)',
                         'প্রাকৃতিক জল ধারণ ক্ষমতা ৩৫% বেড়েছে',
                         'পরিবেশগত টেকসইতা রেটিং: A+',
                         'রাসায়নিক উপকরণে সাশ্রয়: প্রতি একরে ৩,২০০ টাকা'],
  'what_should_i_do_bn': ['জৈব মালচিং ও জীবাণুসমৃদ্ধ জীবামৃত প্রয়োগ চালিয়ে যান',
                          'প্রিমিয়াম জৈব বাজারের সার্টিফিকেশনমূল্য পাওয়ার জন্য প্রস্তুত হন',
                          'জৈব জীবাণু নেটওয়ার্ক সংরক্ষণে মাটির আবরণ বজায় রাখুন']},
 {'scenario_id': 'sc_waterlogging_excess_rain',
  'title': 'Soil Waterlogging & Anoxia Hazard',
  'category': 'Excess Moisture',
  'description': 'Continuous heavy rainfall saturated soil to 96% moisture, creating root anoxia and nutrient '
                 'denitrification conditions.',
  'tags': ['Waterlogging', 'Drainage Required', 'Root Rot Risk'],
  'changes_summary': ['Soil moisture reached 96% (Saturation / Standing water)',
                      'Soil oxygen diffusion rate severely reduced',
                      'Degradation risk flags root asphyxiation'],
  'what_should_i_do': ['Open drainage channels immediately to discharge excess surface water',
                       'Suspend all fertilizer applications until soil reaches field capacity',
                       'Monitor for root rot symptoms and apply bio-drainage techniques'],
  'expected_impact': {'water_requirement_l': 0,
                      'estimated_cost_inr': 150,
                      'soil_health_score': 49,
                      'drainage_urgency': 'High - prevent standing water > 48 hrs',
                      'drainage_urgency_bn': 'উচ্চ - ৪৮ ঘণ্টার বেশি জলাবদ্ধতা প্রতিরোধ করুন'},
  'target_state': {'soil_moisture': 96.0,
                   'soil_temperature': 24.0,
                   'nitrogen': 42.0,
                   'phosphorus': 62.0,
                   'potassium': 58.0,
                   'ph': 6.8,
                   'ec': 0.5,
                   'air_temperature': 25.0,
                   'humidity': 96.0,
                   'rain_probability': 90.0,
                   'expected_rainfall': 45.0,
                   'organic_matter': 1.4},
  'title_bn': 'মাটিতে জলাবদ্ধতা ও অক্সিজেন ঘাটতির ঝুঁকি',
  'category_bn': 'অতিরিক্ত আর্দ্রতা',
  'description_bn': 'ধারাবাহিক ভারী বৃষ্টিতে মাটির আর্দ্রতা ৯৬%-এ পৌঁছেছে, ফলে শিকড়ে অক্সিজেনের ঘাটতি এবং পুষ্টির '
                    'ডিনাইট্রিফিকেশন তৈরি হচ্ছে।',
  'tags_bn': ['জলাবদ্ধতা', 'নিষ্কাশন প্রয়োজন', 'শিকড় পচনের ঝুঁকি'],
  'changes_summary_bn': ['মাটির আর্দ্রতা ৯৬%-এ পৌঁছেছে (সম্পৃক্ত/স্থির জল)',
                         'মাটিতে অক্সিজেনের বিস্তার হার গুরুতরভাবে কমেছে',
                         'অবক্ষয়ের ঝুঁকিতে শিকড়ের শ্বাসরোধ শনাক্ত হয়েছে'],
  'what_should_i_do_bn': ['অতিরিক্ত উপরিভাগের জল সরাতে অবিলম্বে নিষ্কাশন নালা খুলুন',
                          'মাটি ফিল্ড ক্যাপাসিটিতে না আসা পর্যন্ত সব সার প্রয়োগ স্থগিত রাখুন',
                          'শিকড় পচনের লক্ষণ পর্যবেক্ষণ করুন এবং জৈব নিষ্কাশন পদ্ধতি প্রয়োগ করুন']}]
